model:
  name: "canopylabs/orpheus-3b-0.1-pretrained"
  max_model_len: 8192
  device: "cuda"

dataset:
  processed_audio_dir: "processed_samples"
  transcript_dir: "transcripts"
  sample_rate: 24000
  max_duration: 15

training:
  output_dir: "models/finetuned_orpheus"
  num_train_epochs: 5
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 8
  learning_rate: 5e-5
  warmup_steps: 100
  logging_steps: 10
  save_steps: 100
  eval_steps: 100
  save_total_limit: 3
  fp16: true
  seed: 42

generation:
  max_new_tokens: 125
  temperature: 0.7
  top_k: 50
  repetition_penalty: 1.1
  do_sample: true

logging:
  wandb_project: "orpheus-voice-cloning"
  log_dir: "logs"
